#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    SpringCloudConfigLabel:
        Description: The branch of the config environment to use
        Type: String

    Environment:
        Description: The target environment (tst/stg/prd)
        Type: String

    ProjectName:
        Type: String

    S3TemplatesBucketName:
        Type: String
        Default: "ixortalktooling-prd-aws-cloudformation"

    GitUriPrefix:
        Type: String

    SpringProfilesActive:
        Type: String

    SpringCloudConfigServerURI:
        Type: String

    ConfigServerImageVersion:
        Type: String

Conditions:
    UseBitbucketSsh: !Equals [ !Ref GitUriPrefix, "git@bitbucket.org" ]
    UseGithubSsh: !Equals [ !Ref GitUriPrefix, "git@github.com" ]
    UseSsh: !Or [ Condition: UseBitbucketSsh, Condition: UseGithubSsh ]
    UseHttps: !Equals [ !Ref GitUriPrefix, "https" ]


Resources:

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: configserver-logs
            RetentionInDays: 365

    SshConfigserverTaskDefinition:
        Type: AWS::CloudFormation::Stack
        Condition: UseSsh
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/services/core/configserver.ssh.taskdefinition.yaml
            Parameters:
                SpringCloudConfigServerURI: !Ref SpringCloudConfigServerURI
                SpringCloudConfigLabel: !Ref SpringCloudConfigLabel
                SpringProfilesActive: !Ref SpringProfilesActive
                ConfigServerImageVersion: !Ref ConfigServerImageVersion
                GitHost: !If [ UseBitbucketSsh, Bitbucket, Github ]
                ContainerPort: 8899
                LogGroupName: configserver-logs
                ContainerDefinitionName: ixortalk-configserver
                ContainerImage: !Sub ixortalk/ixortalk-config-server:${ConfigServerImageVersion}
                ContainerMemory: 1024

    HttpsConfigserverTaskDefinition:
        Type: AWS::CloudFormation::Stack
        Condition: UseHttps
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/services/core/configserver.https.taskdefinition.yaml
            Parameters:
                SpringCloudConfigServerURI: !Ref SpringCloudConfigServerURI
                SpringCloudConfigLabel: !Ref SpringCloudConfigLabel
                SpringProfilesActive: !Ref SpringProfilesActive
                ConfigServerImageVersion: !Ref ConfigServerImageVersion
                ContainerPort: 8899
                LogGroupName: configserver-logs
                ContainerDefinitionName: ixortalk-configserver
                ContainerImage: !Sub ixortalk/ixortalk-config-server:${ConfigServerImageVersion}
                ContainerMemory: 1024

Outputs:
    TaskDefinition:
        Value: !If [ UseSsh, !GetAtt SshConfigserverTaskDefinition.Outputs.TaskDefinition, !GetAtt HttpsConfigserverTaskDefinition.Outputs.TaskDefinition ]
