#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    SpringCloudConfigLabel:
       Description: The branch of the config environment to use
       Type: String

    LoadbalancerDNS:
        Type: String

    SpringProfilesActive:
        Type: String

    UserRegistrationUiImageVersion:
        Type: String

Resources:

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: ixortalk-user-registration-ui
            ContainerDefinitions:
                - Name: ixortalk-user-registration-ui
                  Image: !Sub ixortalk/ixortalk-user-registration-ui:${UserRegistrationUiImageVersion}
                  Memory: 64
                  Environment:
                  - Name: "IXORTALK_PROFILE"
                    Value: !Ref SpringProfilesActive
                  - Name: "IXORTALK_CONFIG_SERVER_URL"
                    Value: !Sub https://${LoadbalancerDNS}/config
                  - Name: "IXORTALK_CONFIG_SERVER_LABEL"
                    Value: !Ref SpringCloudConfigLabel
                  PortMappings:
                    - ContainerPort: 7005
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: user-registration-ui-logs
                        awslogs-region: !Ref AWS::Region

    UserRegistrationUiCloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties:
            LogGroupName: user-registration-ui-logs
            RetentionInDays: 365

Outputs:
    TaskDefinition:
        Value: !Ref TaskDefinition
