AWSTemplateFormatVersion: '2010-09-09'

Description: |
  Setup PostgreSQL DB Setup custom resource resources


Parameters:

  RDSCustomResourcePSQLDbS3Bucket:
    Type: String

  RDSCustomResourcePSQLDbS3Key:
    Type: String

Resources:

  ManagePgsqlDbs:
    Type: AWS::Lambda::Function
    Properties:
      Handler: "manage-pgsql-dbs.lambda_handler"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/LambdaBasicExecutionRole"
      Code:
        S3Bucket: !Ref RDSCustomResourcePSQLDbS3Bucket
        S3Key: !Ref RDSCustomResourcePSQLDbS3Key
      Runtime: "python3.7"
      Timeout: 300
      VpcConfig:
        SubnetIds:
        - !ImportValue vpc:PrivateSubnet1
        - !ImportValue vpc:PrivateSubnet2
        SecurityGroupIds:
        - !ImportValue vpc:ECSHostSecurityGroup

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ManagePgsqlDbs
      Principal: "sns.amazonaws.com"
      SourceArn: !Ref SNSTopic


  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: psqldb-cr
      Subscription:
      - Endpoint: !GetAtt ManagePgsqlDbs.Arn
        Protocol: lambda
      TopicName: cfn-manage-pgsql-dbs-cr


Outputs:
  serviceToken:
    Value: !Ref SNSTopic
    Export:
      Name: "pgsqlDbCr:serviceToken"