#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    ProjectName:
        Type: String
        Default: demo

    Environment:
        Type: String
        Default: tst

    S3TemplatesBucketName:
        Type: String
        Default: "ixortalktooling-prd-aws-cloudformation"

    HostedZoneNameWithoutDot:
        Type: String
        Default: yourdomain.com

    CloudFrontCertificateARN:
        Description: The Certificate ARN to be used for the cloudfront distribution
        Type: String

Conditions:
  IsProd: !Equals ["prod", !Ref Environment]

Resources:

    CloudFront:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/cloudfront.yaml
            Parameters:
                AssetsBucketName: !Sub ixortalk-${ProjectName}-assets-${Environment}
                CertificateARN: !Ref CloudFrontCertificateARN
                DistributionAlias: !Join
                  - "."
                  - - !If [ IsProd, assets, !Sub "assets-${Environment}"]
                    - !Ref HostedZoneNameWithoutDot
