#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    LBCertificateARN:
          Description: The Certificate ARN to be used for the ELB
          Type: String

    ProjectName:
        Type: String
        Default: demo

    Environment:
        Type: String
        Default: tst

    S3TemplatesBucketName:
        Type: String
        Default: "ixortalktooling-prd-aws-cloudformation"

    HostedZoneName:
        Type: String
        Default: yourdomain.com.

    SubdomainExternal:
        Type: String
        Default: www

    EC2HostSSHKeyName:
        Description: Optional SSH Key for the EC2 Hosts
        Type: String
        Default: ""

    InstanceType:
        Default: t2.large
        Type: String

Resources:

    BastionHost:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/bastion-host.yaml
            Parameters:
                ImageId: ami-29ae2546
                InstanceType: t2.micro
                SecurityGroup: !ImportValue "vpc:BastionHostSecurityGroup"
                EC2HostSSHKeyName: !Ref EC2HostSSHKeyName
                SubnetId: !ImportValue "vpc:PublicSubnet1"

    EFS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/efs.yaml
            Parameters:
                PrivateSubnet1: !ImportValue "vpc:PrivateSubnet1"
                PrivateSubnet2: !ImportValue "vpc:PrivateSubnet2"
                EFSMountTargetSecurityGroup: !ImportValue "vpc:EFSMountTargetSecurityGroup"

    ECSCluster:
        DependsOn:
            - Route53
            - EFS
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/ecs-cluster.yaml
            Parameters:
                ECSBucket: !Sub ixortalk-${ProjectName}-ecs-${Environment}
                ECSHostRole: !GetAtt Roles.Outputs.ECSHostRole
                HostedZoneName: !Ref HostedZoneName
                InstanceType: !Ref InstanceType
                SecurityGroup: !ImportValue "vpc:ECSHostSecurityGroup"
                EC2HostSSHKeyName: !Ref EC2HostSSHKeyName
                Subnets: !ImportValue "vpc:PrivateSubnets"
                VPC: !ImportValue "vpc:VPC"
                EFSFileSystemID: !GetAtt EFS.Outputs.EFSFileSystemID

    ExternalLB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/load-balancer.yaml
            Parameters:
                CertificateARN: !Ref LBCertificateARN
                HTTPListenerExportName: ecs-infra:ExternalLB-HTTP-Listener
                HTTPSListenerExportName: ecs-infra:ExternalLB-HTTPS-Listener
                LoadBalancerName: External-Loadbalancer
                LoadBalancerDNSExportName: ecs-infra:ExternalLB-DNS
                Scheme: internet-facing
                SecurityGroup: !ImportValue "vpc:ExternalLBSecurityGroup"
                Subnets: !ImportValue "vpc:PublicSubnets"
                VPC: !ImportValue "vpc:VPC"

    InternalLB:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/load-balancer.yaml
            Parameters:
                CertificateARN: !Ref LBCertificateARN
                HTTPSListenerExportName: ecs-infra:InternalLB-HTTPS-Listener
                LoadBalancerName: Internal-Loadbalancer
                LoadBalancerDNSExportName: ecs-infra:InternalLB-DNS
                Scheme: internal
                SecurityGroup: !ImportValue "vpc:InternalLBSecurityGroup"
                Subnets: !ImportValue "vpc:PrivateSubnets"
                VPC: !ImportValue "vpc:VPC"

    Route53:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/route53.yaml
            Parameters:
                HostedZoneName: !Ref HostedZoneName
                InternalRecordDNSName: !GetAtt InternalLB.Outputs.LoadbalancerDNS
                VPC: !ImportValue "vpc:VPC"

    Roles:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/roles.yaml
            Parameters:
                ECSBucketArn: !Sub arn:aws:s3:::ixortalk-${ProjectName}-ecs-${Environment}


                
Outputs:
    WebsiteServiceUrl:
        Description: The URL endpoint for the website service
        Value: !Sub https://${SubdomainExternal}.${HostedZoneName}
