#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    ProjectName:
        Type: String
        Default: demo

    Environment:
        Type: String
        Default: tst

    S3TemplatesBucketName:
        Type: String
        Default: "ixortalktooling-prd-aws-cloudformation"

    AuthDBMasterPassword:
        Description: Password for admin user
        Type: String
        Default: SuperSecurePassword

    AuthDBStorage:
        Type: Number
        Default: 5

    RDSCustomResourcePSQLDbS3Bucket:
        Type: String
        Default: ixortooling-prd-s3-lambda-function-store-public

    RDSCustomResourcePSQLDbS3Key:
        Type: String
        Default: aws-lambda-manage-pgsql-dbs-17ae2642d4dc6aeee84dbaa4dd7edc09a50d4b43.zip

    IxorTalkAuthorizationServerDBPassword:
        Type: String
        Default: SuperSecurePassword


Resources:

        RDSAuth:
            Type: AWS::CloudFormation::Stack
            Properties:
                TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/rds.yaml
                Parameters:
                    JDBCConnectionStringExportName: "rds:AuthRDS-JDBCConnectionString"
                    DBName: AuthDatabase
                    MasterPassword: !Ref AuthDBMasterPassword
                    SourceSecurityGroup: !ImportValue "vpc:ECSHostSecurityGroup"
                    Subnets: !ImportValue "vpc:PrivateSubnets"
                    VPC: !ImportValue "vpc:VPC"
                    Storage: !Ref AuthDBStorage
                    ProjectName: !Ref ProjectName
                    Environment: !Ref Environment

        RDSCustomResourcePSQLDb:
            Type: AWS::CloudFormation::Stack
            Properties:
                TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/rds-custom-resource-psql-db.yaml
                Parameters:
                    RDSCustomResourcePSQLDbS3Bucket: !Ref RDSCustomResourcePSQLDbS3Bucket
                    RDSCustomResourcePSQLDbS3Key: !Ref RDSCustomResourcePSQLDbS3Key

        AuthorizationServerDB:
            Type: Custom::PgSqlDB
            DependsOn:
                - RDSCustomResourcePSQLDb
            Properties:
                loglevel: "DEBUG"

                ServiceToken: !GetAtt RDSCustomResourcePSQLDb.Outputs.serviceToken

                DBHost: !ImportValue "rds:AuthDatabase-RDSHost"
                DBRootUser: "root"
                DBRootPassword: !Ref AuthDBMasterPassword

                DBToCreate: "IxorTalkAuthorizationServerDB"
                DBUser: "ixortalk_authorization_server"
                DBPassword: !Ref IxorTalkAuthorizationServerDBPassword


Outputs:

    AuthorizationServerDBJDBCConnectionString:
        Value: !GetAtt AuthorizationServerDB.JDBCConnectionString
        Export:
            Name: "rds:AuthorizationServerDB-JDBCConnectionString"

    AuthorizationServerDBJDBCUsername:
        Value: !GetAtt AuthorizationServerDB.JDBCUsername
        Export:
            Name: "rds:AuthorizationServerDB-JDBCUsername"

    AuthorizationServerDBJDBCPassword:
        Value: !GetAtt AuthorizationServerDB.JDBCPassword
        Export:
            Name: "rds:AuthorizationServerDB-JDBCPassword"