#
# MIT License
#
# Copyright (c) 2018 IxorTalk CVBA
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

AWSTemplateFormatVersion: "2010-09-09"

Parameters:

    ProjectName:
        Type: String
        Default: demo

    Environment:
        Type: String
        Default: tst

    S3TemplatesBucketName:
        Type: String
        Default: "ixortalktooling-prd-aws-cloudformation"

    VpcCIDR:
        Type: String
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$
        Default: "10.10.0.0/16"

    BastionIngressCidrIp:
        Type: String
        Default: "0.0.0.0/0"
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$

    PublicSubnet1CIDR:
        Type: String
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$
        Default: "10.10.8.0/21"

    PublicSubnet2CIDR:
        Type: String
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$
        Default: "10.10.16.0/21"

    PrivateSubnet1CIDR:
        Type: String
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$
        Default: "10.10.24.0/21"

    PrivateSubnet2CIDR:
        Type: String
        AllowedPattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}(/([0-9]|[1-2][0-9]|3[0-2]))?$
        Default: "10.10.32.0/21"



Resources:

    SecurityGroups:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/security-groups.yaml
            Parameters:
                VPC: !GetAtt VPC.Outputs.VPC
                VpcCIDR: !Ref VpcCIDR
                BastionIngressCidrIp: !Ref BastionIngressCidrIp

    VPC:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/vpc.yaml
            Parameters:
                PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
                PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
                ProjectName: !Ref ProjectName
                PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
                PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
                VpcCIDR: !Ref VpcCIDR

    EFS:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.eu-central-1.amazonaws.com/${S3TemplatesBucketName}/infrastructure/efs.yaml
            Parameters:
                PrivateSubnet1: !ImportValue "vpc:PrivateSubnet1"
                PrivateSubnet2: !ImportValue "vpc:PrivateSubnet2"
                EFSMountTargetSecurityGroup: !ImportValue "vpc:EFSMountTargetSecurityGroup"